name: Auto Linter
on:
  push:
    paths: "*.py"

jobs:
  code:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout/Clone the code
        uses: actions/checkout@v7
      - name: Install Linter
        run: pip install ruff
      - name: Check the files for linting
        run: ruff check .

