name: CICD
on:
  workflow_dispatch:

jobs:
  code:
    runs-on: ubuntu-latest
    steps:
      - name: Clone the Code
        run: echo "Cloning the Code"


  build:
    needs: [code]
    runs-on: ubuntu-latest
    steps:
      - name: Build the Code
        run: echo "Building the Code"

  test:
    needs: [build]
    runs-on: ubuntu-latest
    steps:
      - name: Test the Code
        run: echo "Testing the Code"

  deploy:
    needs: [build, test]
    runs-on: ubuntu-latest
    steps:
      - name: Deploy the Code
        run: echo "Deploying the Code"
