name: CICD
on:
  workflow_dispatch:

jobs:
  code:
    runs-on: ubuntu-latest
    steps:
      - name: Clone the Code
        run: echo "Cloning the Code"


  build:
    runs-on: ubuntu-latest
    steps:
      - name: Build the Code
        run: echo "Building the Code"

  test:
    runs-on: ubuntu-latest
    steps:
      - name: Test the Code
        run: echo "Testing the Code"
